### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by radupasparuga** [radupasparuga/WorldWideStudents#1]
- [x] Create register system
- [x] Create login system
- [x] Verify if username/email is already taken
- [ ] Create profile page for each user
- [ ] User can upload profile pic
- [ ] Users must choose a country of provenience 
- [ ] Page where you can see all users and sort them by country
- [ ] Ability to follow users
- [ ] Ability to post things(images, text)
- [ ] Dashboard page to see posts from followed users
- [ ] Like/other reactions to posts
- [ ] Comment to posts
- [ ] User profile page to have posts made by them(maybe comments too)
- [ ] Ability to chat with other users(socket.io)
- [ ] ~Not certain~ ability to video call other users
- [ ] ~Not certain~ Add login with google/fb etc.
